name: GitHub Release

on:
  workflow_run:
    workflows: ["Publish to npm"]
    types:
      - completed

jobs:
  github-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version and changelog from CHANGELOG.md
        id: changelog
        run: |
          VERSION=$(grep -m1 -oP '^## \[\K[^\]]+' CHANGELOG.md)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          BODY=$(awk "/## \[$VERSION\]/,/^---/" CHANGELOG.md | sed '1d;$d' | sed '/./,$!d')
          echo "changelog<<EOF" >> $GITHUB_ENV
          echo "$BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.changelog.outputs.version }}
          name: Release v${{ steps.changelog.outputs.version }}
          body: ${{ env.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
